// Code generated by ent, DO NOT EDIT.

package dao

import (
	"aisecurity/ent/dao/admin"
	"aisecurity/ent/dao/adminrole"
	"aisecurity/ent/dao/predicate"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminRoleQuery is the builder for querying AdminRole entities.
type AdminRoleQuery struct {
	config
	ctx         *QueryContext
	order       []adminrole.OrderOption
	inters      []Interceptor
	predicates  []predicate.AdminRole
	withCreator *AdminQuery
	withUpdator *AdminQuery
	withAdmins  *AdminQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AdminRoleQuery builder.
func (arq *AdminRoleQuery) Where(ps ...predicate.AdminRole) *AdminRoleQuery {
	arq.predicates = append(arq.predicates, ps...)
	return arq
}

// Limit the number of records to be returned by this query.
func (arq *AdminRoleQuery) Limit(limit int) *AdminRoleQuery {
	arq.ctx.Limit = &limit
	return arq
}

// Offset to start from.
func (arq *AdminRoleQuery) Offset(offset int) *AdminRoleQuery {
	arq.ctx.Offset = &offset
	return arq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (arq *AdminRoleQuery) Unique(unique bool) *AdminRoleQuery {
	arq.ctx.Unique = &unique
	return arq
}

// Order specifies how the records should be ordered.
func (arq *AdminRoleQuery) Order(o ...adminrole.OrderOption) *AdminRoleQuery {
	arq.order = append(arq.order, o...)
	return arq
}

// QueryCreator chains the current query on the "creator" edge.
func (arq *AdminRoleQuery) QueryCreator() *AdminQuery {
	query := (&AdminClient{config: arq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := arq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := arq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adminrole.Table, adminrole.FieldID, selector),
			sqlgraph.To(admin.Table, admin.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adminrole.CreatorTable, adminrole.CreatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(arq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUpdator chains the current query on the "updator" edge.
func (arq *AdminRoleQuery) QueryUpdator() *AdminQuery {
	query := (&AdminClient{config: arq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := arq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := arq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adminrole.Table, adminrole.FieldID, selector),
			sqlgraph.To(admin.Table, admin.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, adminrole.UpdatorTable, adminrole.UpdatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(arq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAdmins chains the current query on the "admins" edge.
func (arq *AdminRoleQuery) QueryAdmins() *AdminQuery {
	query := (&AdminClient{config: arq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := arq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := arq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(adminrole.Table, adminrole.FieldID, selector),
			sqlgraph.To(admin.Table, admin.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, adminrole.AdminsTable, adminrole.AdminsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(arq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first AdminRole entity from the query.
// Returns a *NotFoundError when no AdminRole was found.
func (arq *AdminRoleQuery) First(ctx context.Context) (*AdminRole, error) {
	nodes, err := arq.Limit(1).All(setContextOp(ctx, arq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{adminrole.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (arq *AdminRoleQuery) FirstX(ctx context.Context) *AdminRole {
	node, err := arq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AdminRole ID from the query.
// Returns a *NotFoundError when no AdminRole ID was found.
func (arq *AdminRoleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = arq.Limit(1).IDs(setContextOp(ctx, arq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{adminrole.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (arq *AdminRoleQuery) FirstIDX(ctx context.Context) int {
	id, err := arq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AdminRole entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AdminRole entity is found.
// Returns a *NotFoundError when no AdminRole entities are found.
func (arq *AdminRoleQuery) Only(ctx context.Context) (*AdminRole, error) {
	nodes, err := arq.Limit(2).All(setContextOp(ctx, arq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{adminrole.Label}
	default:
		return nil, &NotSingularError{adminrole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (arq *AdminRoleQuery) OnlyX(ctx context.Context) *AdminRole {
	node, err := arq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AdminRole ID in the query.
// Returns a *NotSingularError when more than one AdminRole ID is found.
// Returns a *NotFoundError when no entities are found.
func (arq *AdminRoleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = arq.Limit(2).IDs(setContextOp(ctx, arq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{adminrole.Label}
	default:
		err = &NotSingularError{adminrole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (arq *AdminRoleQuery) OnlyIDX(ctx context.Context) int {
	id, err := arq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AdminRoles.
func (arq *AdminRoleQuery) All(ctx context.Context) ([]*AdminRole, error) {
	ctx = setContextOp(ctx, arq.ctx, "All")
	if err := arq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AdminRole, *AdminRoleQuery]()
	return withInterceptors[[]*AdminRole](ctx, arq, qr, arq.inters)
}

// AllX is like All, but panics if an error occurs.
func (arq *AdminRoleQuery) AllX(ctx context.Context) []*AdminRole {
	nodes, err := arq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AdminRole IDs.
func (arq *AdminRoleQuery) IDs(ctx context.Context) (ids []int, err error) {
	if arq.ctx.Unique == nil && arq.path != nil {
		arq.Unique(true)
	}
	ctx = setContextOp(ctx, arq.ctx, "IDs")
	if err = arq.Select(adminrole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (arq *AdminRoleQuery) IDsX(ctx context.Context) []int {
	ids, err := arq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (arq *AdminRoleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, arq.ctx, "Count")
	if err := arq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, arq, querierCount[*AdminRoleQuery](), arq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (arq *AdminRoleQuery) CountX(ctx context.Context) int {
	count, err := arq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (arq *AdminRoleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, arq.ctx, "Exist")
	switch _, err := arq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("dao: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (arq *AdminRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := arq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AdminRoleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (arq *AdminRoleQuery) Clone() *AdminRoleQuery {
	if arq == nil {
		return nil
	}
	return &AdminRoleQuery{
		config:      arq.config,
		ctx:         arq.ctx.Clone(),
		order:       append([]adminrole.OrderOption{}, arq.order...),
		inters:      append([]Interceptor{}, arq.inters...),
		predicates:  append([]predicate.AdminRole{}, arq.predicates...),
		withCreator: arq.withCreator.Clone(),
		withUpdator: arq.withUpdator.Clone(),
		withAdmins:  arq.withAdmins.Clone(),
		// clone intermediate query.
		sql:  arq.sql.Clone(),
		path: arq.path,
	}
}

// WithCreator tells the query-builder to eager-load the nodes that are connected to
// the "creator" edge. The optional arguments are used to configure the query builder of the edge.
func (arq *AdminRoleQuery) WithCreator(opts ...func(*AdminQuery)) *AdminRoleQuery {
	query := (&AdminClient{config: arq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	arq.withCreator = query
	return arq
}

// WithUpdator tells the query-builder to eager-load the nodes that are connected to
// the "updator" edge. The optional arguments are used to configure the query builder of the edge.
func (arq *AdminRoleQuery) WithUpdator(opts ...func(*AdminQuery)) *AdminRoleQuery {
	query := (&AdminClient{config: arq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	arq.withUpdator = query
	return arq
}

// WithAdmins tells the query-builder to eager-load the nodes that are connected to
// the "admins" edge. The optional arguments are used to configure the query builder of the edge.
func (arq *AdminRoleQuery) WithAdmins(opts ...func(*AdminQuery)) *AdminRoleQuery {
	query := (&AdminClient{config: arq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	arq.withAdmins = query
	return arq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AdminRole.Query().
//		GroupBy(adminrole.FieldCreatedAt).
//		Aggregate(dao.Count()).
//		Scan(ctx, &v)
func (arq *AdminRoleQuery) GroupBy(field string, fields ...string) *AdminRoleGroupBy {
	arq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AdminRoleGroupBy{build: arq}
	grbuild.flds = &arq.ctx.Fields
	grbuild.label = adminrole.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at"`
//	}
//
//	client.AdminRole.Query().
//		Select(adminrole.FieldCreatedAt).
//		Scan(ctx, &v)
func (arq *AdminRoleQuery) Select(fields ...string) *AdminRoleSelect {
	arq.ctx.Fields = append(arq.ctx.Fields, fields...)
	sbuild := &AdminRoleSelect{AdminRoleQuery: arq}
	sbuild.label = adminrole.Label
	sbuild.flds, sbuild.scan = &arq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AdminRoleSelect configured with the given aggregations.
func (arq *AdminRoleQuery) Aggregate(fns ...AggregateFunc) *AdminRoleSelect {
	return arq.Select().Aggregate(fns...)
}

func (arq *AdminRoleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range arq.inters {
		if inter == nil {
			return fmt.Errorf("dao: uninitialized interceptor (forgotten import dao/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, arq); err != nil {
				return err
			}
		}
	}
	for _, f := range arq.ctx.Fields {
		if !adminrole.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("dao: invalid field %q for query", f)}
		}
	}
	if arq.path != nil {
		prev, err := arq.path(ctx)
		if err != nil {
			return err
		}
		arq.sql = prev
	}
	return nil
}

func (arq *AdminRoleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AdminRole, error) {
	var (
		nodes       = []*AdminRole{}
		_spec       = arq.querySpec()
		loadedTypes = [3]bool{
			arq.withCreator != nil,
			arq.withUpdator != nil,
			arq.withAdmins != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AdminRole).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AdminRole{config: arq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, arq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := arq.withCreator; query != nil {
		if err := arq.loadCreator(ctx, query, nodes, nil,
			func(n *AdminRole, e *Admin) { n.Edges.Creator = e }); err != nil {
			return nil, err
		}
	}
	if query := arq.withUpdator; query != nil {
		if err := arq.loadUpdator(ctx, query, nodes, nil,
			func(n *AdminRole, e *Admin) { n.Edges.Updator = e }); err != nil {
			return nil, err
		}
	}
	if query := arq.withAdmins; query != nil {
		if err := arq.loadAdmins(ctx, query, nodes,
			func(n *AdminRole) { n.Edges.Admins = []*Admin{} },
			func(n *AdminRole, e *Admin) { n.Edges.Admins = append(n.Edges.Admins, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (arq *AdminRoleQuery) loadCreator(ctx context.Context, query *AdminQuery, nodes []*AdminRole, init func(*AdminRole), assign func(*AdminRole, *Admin)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AdminRole)
	for i := range nodes {
		fk := nodes[i].CreatedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(admin.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "created_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (arq *AdminRoleQuery) loadUpdator(ctx context.Context, query *AdminQuery, nodes []*AdminRole, init func(*AdminRole), assign func(*AdminRole, *Admin)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*AdminRole)
	for i := range nodes {
		fk := nodes[i].UpdatedBy
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(admin.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "updated_by" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (arq *AdminRoleQuery) loadAdmins(ctx context.Context, query *AdminQuery, nodes []*AdminRole, init func(*AdminRole), assign func(*AdminRole, *Admin)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[int]*AdminRole)
	nids := make(map[int]map[*AdminRole]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(adminrole.AdminsTable)
		s.Join(joinT).On(s.C(admin.FieldID), joinT.C(adminrole.AdminsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(adminrole.AdminsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(adminrole.AdminsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := int(values[0].(*sql.NullInt64).Int64)
				inValue := int(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*AdminRole]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Admin](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "admins" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}

func (arq *AdminRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := arq.querySpec()
	_spec.Node.Columns = arq.ctx.Fields
	if len(arq.ctx.Fields) > 0 {
		_spec.Unique = arq.ctx.Unique != nil && *arq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, arq.driver, _spec)
}

func (arq *AdminRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(adminrole.Table, adminrole.Columns, sqlgraph.NewFieldSpec(adminrole.FieldID, field.TypeInt))
	_spec.From = arq.sql
	if unique := arq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if arq.path != nil {
		_spec.Unique = true
	}
	if fields := arq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminrole.FieldID)
		for i := range fields {
			if fields[i] != adminrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if arq.withCreator != nil {
			_spec.Node.AddColumnOnce(adminrole.FieldCreatedBy)
		}
		if arq.withUpdator != nil {
			_spec.Node.AddColumnOnce(adminrole.FieldUpdatedBy)
		}
	}
	if ps := arq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := arq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := arq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := arq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (arq *AdminRoleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(arq.driver.Dialect())
	t1 := builder.Table(adminrole.Table)
	columns := arq.ctx.Fields
	if len(columns) == 0 {
		columns = adminrole.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if arq.sql != nil {
		selector = arq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if arq.ctx.Unique != nil && *arq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range arq.predicates {
		p(selector)
	}
	for _, p := range arq.order {
		p(selector)
	}
	if offset := arq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := arq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AdminRoleGroupBy is the group-by builder for AdminRole entities.
type AdminRoleGroupBy struct {
	selector
	build *AdminRoleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (argb *AdminRoleGroupBy) Aggregate(fns ...AggregateFunc) *AdminRoleGroupBy {
	argb.fns = append(argb.fns, fns...)
	return argb
}

// Scan applies the selector query and scans the result into the given value.
func (argb *AdminRoleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, argb.build.ctx, "GroupBy")
	if err := argb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminRoleQuery, *AdminRoleGroupBy](ctx, argb.build, argb, argb.build.inters, v)
}

func (argb *AdminRoleGroupBy) sqlScan(ctx context.Context, root *AdminRoleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(argb.fns))
	for _, fn := range argb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*argb.flds)+len(argb.fns))
		for _, f := range *argb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*argb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := argb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AdminRoleSelect is the builder for selecting fields of AdminRole entities.
type AdminRoleSelect struct {
	*AdminRoleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ars *AdminRoleSelect) Aggregate(fns ...AggregateFunc) *AdminRoleSelect {
	ars.fns = append(ars.fns, fns...)
	return ars
}

// Scan applies the selector query and scans the result into the given value.
func (ars *AdminRoleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ars.ctx, "Select")
	if err := ars.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AdminRoleQuery, *AdminRoleSelect](ctx, ars.AdminRoleQuery, ars, ars.inters, v)
}

func (ars *AdminRoleSelect) sqlScan(ctx context.Context, root *AdminRoleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ars.fns))
	for _, fn := range ars.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ars.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ars.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
