// Code generated by ent, DO NOT EDIT.

package dao

import (
	"aisecurity/ent/dao/admin"
	"aisecurity/ent/dao/department"
	"aisecurity/ent/dao/employee"
	"aisecurity/ent/dao/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmployeeUpdate is the builder for updating Employee entities.
type EmployeeUpdate struct {
	config
	hooks    []Hook
	mutation *EmployeeMutation
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (eu *EmployeeUpdate) Where(ps ...predicate.Employee) *EmployeeUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetCreatedBy sets the "created_by" field.
func (eu *EmployeeUpdate) SetCreatedBy(i int) *EmployeeUpdate {
	eu.mutation.SetCreatedBy(i)
	return eu
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableCreatedBy(i *int) *EmployeeUpdate {
	if i != nil {
		eu.SetCreatedBy(*i)
	}
	return eu
}

// SetAdminID sets the "admin_id" field.
func (eu *EmployeeUpdate) SetAdminID(i int) *EmployeeUpdate {
	eu.mutation.SetAdminID(i)
	return eu
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableAdminID(i *int) *EmployeeUpdate {
	if i != nil {
		eu.SetAdminID(*i)
	}
	return eu
}

// SetDepartmentID sets the "department_id" field.
func (eu *EmployeeUpdate) SetDepartmentID(i int) *EmployeeUpdate {
	eu.mutation.SetDepartmentID(i)
	return eu
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableDepartmentID(i *int) *EmployeeUpdate {
	if i != nil {
		eu.SetDepartmentID(*i)
	}
	return eu
}

// SetDeletedAt sets the "deleted_at" field.
func (eu *EmployeeUpdate) SetDeletedAt(t time.Time) *EmployeeUpdate {
	eu.mutation.SetDeletedAt(t)
	return eu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableDeletedAt(t *time.Time) *EmployeeUpdate {
	if t != nil {
		eu.SetDeletedAt(*t)
	}
	return eu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (eu *EmployeeUpdate) ClearDeletedAt() *EmployeeUpdate {
	eu.mutation.ClearDeletedAt()
	return eu
}

// SetUpdatedBy sets the "updated_by" field.
func (eu *EmployeeUpdate) SetUpdatedBy(i int) *EmployeeUpdate {
	eu.mutation.ResetUpdatedBy()
	eu.mutation.SetUpdatedBy(i)
	return eu
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (eu *EmployeeUpdate) SetNillableUpdatedBy(i *int) *EmployeeUpdate {
	if i != nil {
		eu.SetUpdatedBy(*i)
	}
	return eu
}

// AddUpdatedBy adds i to the "updated_by" field.
func (eu *EmployeeUpdate) AddUpdatedBy(i int) *EmployeeUpdate {
	eu.mutation.AddUpdatedBy(i)
	return eu
}

// SetUpdatedAt sets the "updated_at" field.
func (eu *EmployeeUpdate) SetUpdatedAt(t time.Time) *EmployeeUpdate {
	eu.mutation.SetUpdatedAt(t)
	return eu
}

// SetCreatorID sets the "creator" edge to the Admin entity by ID.
func (eu *EmployeeUpdate) SetCreatorID(id int) *EmployeeUpdate {
	eu.mutation.SetCreatorID(id)
	return eu
}

// SetCreator sets the "creator" edge to the Admin entity.
func (eu *EmployeeUpdate) SetCreator(a *Admin) *EmployeeUpdate {
	return eu.SetCreatorID(a.ID)
}

// SetAdmin sets the "admin" edge to the Admin entity.
func (eu *EmployeeUpdate) SetAdmin(a *Admin) *EmployeeUpdate {
	return eu.SetAdminID(a.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (eu *EmployeeUpdate) SetDepartment(d *Department) *EmployeeUpdate {
	return eu.SetDepartmentID(d.ID)
}

// Mutation returns the EmployeeMutation object of the builder.
func (eu *EmployeeUpdate) Mutation() *EmployeeMutation {
	return eu.mutation
}

// ClearCreator clears the "creator" edge to the Admin entity.
func (eu *EmployeeUpdate) ClearCreator() *EmployeeUpdate {
	eu.mutation.ClearCreator()
	return eu
}

// ClearAdmin clears the "admin" edge to the Admin entity.
func (eu *EmployeeUpdate) ClearAdmin() *EmployeeUpdate {
	eu.mutation.ClearAdmin()
	return eu
}

// ClearDepartment clears the "department" edge to the Department entity.
func (eu *EmployeeUpdate) ClearDepartment() *EmployeeUpdate {
	eu.mutation.ClearDepartment()
	return eu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EmployeeUpdate) Save(ctx context.Context) (int, error) {
	eu.defaults()
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EmployeeUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EmployeeUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EmployeeUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eu *EmployeeUpdate) defaults() {
	if _, ok := eu.mutation.UpdatedAt(); !ok {
		v := employee.UpdateDefaultUpdatedAt()
		eu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EmployeeUpdate) check() error {
	if v, ok := eu.mutation.CreatedBy(); ok {
		if err := employee.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`dao: validator failed for field "Employee.created_by": %w`, err)}
		}
	}
	if v, ok := eu.mutation.AdminID(); ok {
		if err := employee.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`dao: validator failed for field "Employee.admin_id": %w`, err)}
		}
	}
	if v, ok := eu.mutation.DepartmentID(); ok {
		if err := employee.DepartmentIDValidator(v); err != nil {
			return &ValidationError{Name: "department_id", err: fmt.Errorf(`dao: validator failed for field "Employee.department_id": %w`, err)}
		}
	}
	if v, ok := eu.mutation.UpdatedBy(); ok {
		if err := employee.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`dao: validator failed for field "Employee.updated_by": %w`, err)}
		}
	}
	if _, ok := eu.mutation.CreatorID(); eu.mutation.CreatorCleared() && !ok {
		return errors.New(`dao: clearing a required unique edge "Employee.creator"`)
	}
	if _, ok := eu.mutation.AdminID(); eu.mutation.AdminCleared() && !ok {
		return errors.New(`dao: clearing a required unique edge "Employee.admin"`)
	}
	if _, ok := eu.mutation.DepartmentID(); eu.mutation.DepartmentCleared() && !ok {
		return errors.New(`dao: clearing a required unique edge "Employee.department"`)
	}
	return nil
}

func (eu *EmployeeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.DeletedAt(); ok {
		_spec.SetField(employee.FieldDeletedAt, field.TypeTime, value)
	}
	if eu.mutation.DeletedAtCleared() {
		_spec.ClearField(employee.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := eu.mutation.UpdatedBy(); ok {
		_spec.SetField(employee.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := eu.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(employee.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := eu.mutation.UpdatedAt(); ok {
		_spec.SetField(employee.FieldUpdatedAt, field.TypeTime, value)
	}
	if eu.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.CreatorTable,
			Columns: []string{employee.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.CreatorTable,
			Columns: []string{employee.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.AdminTable,
			Columns: []string{employee.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.AdminTable,
			Columns: []string{employee.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EmployeeUpdateOne is the builder for updating a single Employee entity.
type EmployeeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmployeeMutation
}

// SetCreatedBy sets the "created_by" field.
func (euo *EmployeeUpdateOne) SetCreatedBy(i int) *EmployeeUpdateOne {
	euo.mutation.SetCreatedBy(i)
	return euo
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableCreatedBy(i *int) *EmployeeUpdateOne {
	if i != nil {
		euo.SetCreatedBy(*i)
	}
	return euo
}

// SetAdminID sets the "admin_id" field.
func (euo *EmployeeUpdateOne) SetAdminID(i int) *EmployeeUpdateOne {
	euo.mutation.SetAdminID(i)
	return euo
}

// SetNillableAdminID sets the "admin_id" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableAdminID(i *int) *EmployeeUpdateOne {
	if i != nil {
		euo.SetAdminID(*i)
	}
	return euo
}

// SetDepartmentID sets the "department_id" field.
func (euo *EmployeeUpdateOne) SetDepartmentID(i int) *EmployeeUpdateOne {
	euo.mutation.SetDepartmentID(i)
	return euo
}

// SetNillableDepartmentID sets the "department_id" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableDepartmentID(i *int) *EmployeeUpdateOne {
	if i != nil {
		euo.SetDepartmentID(*i)
	}
	return euo
}

// SetDeletedAt sets the "deleted_at" field.
func (euo *EmployeeUpdateOne) SetDeletedAt(t time.Time) *EmployeeUpdateOne {
	euo.mutation.SetDeletedAt(t)
	return euo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableDeletedAt(t *time.Time) *EmployeeUpdateOne {
	if t != nil {
		euo.SetDeletedAt(*t)
	}
	return euo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (euo *EmployeeUpdateOne) ClearDeletedAt() *EmployeeUpdateOne {
	euo.mutation.ClearDeletedAt()
	return euo
}

// SetUpdatedBy sets the "updated_by" field.
func (euo *EmployeeUpdateOne) SetUpdatedBy(i int) *EmployeeUpdateOne {
	euo.mutation.ResetUpdatedBy()
	euo.mutation.SetUpdatedBy(i)
	return euo
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (euo *EmployeeUpdateOne) SetNillableUpdatedBy(i *int) *EmployeeUpdateOne {
	if i != nil {
		euo.SetUpdatedBy(*i)
	}
	return euo
}

// AddUpdatedBy adds i to the "updated_by" field.
func (euo *EmployeeUpdateOne) AddUpdatedBy(i int) *EmployeeUpdateOne {
	euo.mutation.AddUpdatedBy(i)
	return euo
}

// SetUpdatedAt sets the "updated_at" field.
func (euo *EmployeeUpdateOne) SetUpdatedAt(t time.Time) *EmployeeUpdateOne {
	euo.mutation.SetUpdatedAt(t)
	return euo
}

// SetCreatorID sets the "creator" edge to the Admin entity by ID.
func (euo *EmployeeUpdateOne) SetCreatorID(id int) *EmployeeUpdateOne {
	euo.mutation.SetCreatorID(id)
	return euo
}

// SetCreator sets the "creator" edge to the Admin entity.
func (euo *EmployeeUpdateOne) SetCreator(a *Admin) *EmployeeUpdateOne {
	return euo.SetCreatorID(a.ID)
}

// SetAdmin sets the "admin" edge to the Admin entity.
func (euo *EmployeeUpdateOne) SetAdmin(a *Admin) *EmployeeUpdateOne {
	return euo.SetAdminID(a.ID)
}

// SetDepartment sets the "department" edge to the Department entity.
func (euo *EmployeeUpdateOne) SetDepartment(d *Department) *EmployeeUpdateOne {
	return euo.SetDepartmentID(d.ID)
}

// Mutation returns the EmployeeMutation object of the builder.
func (euo *EmployeeUpdateOne) Mutation() *EmployeeMutation {
	return euo.mutation
}

// ClearCreator clears the "creator" edge to the Admin entity.
func (euo *EmployeeUpdateOne) ClearCreator() *EmployeeUpdateOne {
	euo.mutation.ClearCreator()
	return euo
}

// ClearAdmin clears the "admin" edge to the Admin entity.
func (euo *EmployeeUpdateOne) ClearAdmin() *EmployeeUpdateOne {
	euo.mutation.ClearAdmin()
	return euo
}

// ClearDepartment clears the "department" edge to the Department entity.
func (euo *EmployeeUpdateOne) ClearDepartment() *EmployeeUpdateOne {
	euo.mutation.ClearDepartment()
	return euo
}

// Where appends a list predicates to the EmployeeUpdate builder.
func (euo *EmployeeUpdateOne) Where(ps ...predicate.Employee) *EmployeeUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EmployeeUpdateOne) Select(field string, fields ...string) *EmployeeUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Employee entity.
func (euo *EmployeeUpdateOne) Save(ctx context.Context) (*Employee, error) {
	euo.defaults()
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EmployeeUpdateOne) SaveX(ctx context.Context) *Employee {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EmployeeUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EmployeeUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (euo *EmployeeUpdateOne) defaults() {
	if _, ok := euo.mutation.UpdatedAt(); !ok {
		v := employee.UpdateDefaultUpdatedAt()
		euo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EmployeeUpdateOne) check() error {
	if v, ok := euo.mutation.CreatedBy(); ok {
		if err := employee.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`dao: validator failed for field "Employee.created_by": %w`, err)}
		}
	}
	if v, ok := euo.mutation.AdminID(); ok {
		if err := employee.AdminIDValidator(v); err != nil {
			return &ValidationError{Name: "admin_id", err: fmt.Errorf(`dao: validator failed for field "Employee.admin_id": %w`, err)}
		}
	}
	if v, ok := euo.mutation.DepartmentID(); ok {
		if err := employee.DepartmentIDValidator(v); err != nil {
			return &ValidationError{Name: "department_id", err: fmt.Errorf(`dao: validator failed for field "Employee.department_id": %w`, err)}
		}
	}
	if v, ok := euo.mutation.UpdatedBy(); ok {
		if err := employee.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`dao: validator failed for field "Employee.updated_by": %w`, err)}
		}
	}
	if _, ok := euo.mutation.CreatorID(); euo.mutation.CreatorCleared() && !ok {
		return errors.New(`dao: clearing a required unique edge "Employee.creator"`)
	}
	if _, ok := euo.mutation.AdminID(); euo.mutation.AdminCleared() && !ok {
		return errors.New(`dao: clearing a required unique edge "Employee.admin"`)
	}
	if _, ok := euo.mutation.DepartmentID(); euo.mutation.DepartmentCleared() && !ok {
		return errors.New(`dao: clearing a required unique edge "Employee.department"`)
	}
	return nil
}

func (euo *EmployeeUpdateOne) sqlSave(ctx context.Context) (_node *Employee, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(employee.Table, employee.Columns, sqlgraph.NewFieldSpec(employee.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`dao: missing "Employee.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, employee.FieldID)
		for _, f := range fields {
			if !employee.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("dao: invalid field %q for query", f)}
			}
			if f != employee.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.DeletedAt(); ok {
		_spec.SetField(employee.FieldDeletedAt, field.TypeTime, value)
	}
	if euo.mutation.DeletedAtCleared() {
		_spec.ClearField(employee.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := euo.mutation.UpdatedBy(); ok {
		_spec.SetField(employee.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := euo.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(employee.FieldUpdatedBy, field.TypeInt, value)
	}
	if value, ok := euo.mutation.UpdatedAt(); ok {
		_spec.SetField(employee.FieldUpdatedAt, field.TypeTime, value)
	}
	if euo.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.CreatorTable,
			Columns: []string{employee.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.CreatorTable,
			Columns: []string{employee.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.AdminCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.AdminTable,
			Columns: []string{employee.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.AdminIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.AdminTable,
			Columns: []string{employee.AdminColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(admin.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.DepartmentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   employee.DepartmentTable,
			Columns: []string{employee.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(department.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Employee{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{employee.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
