// Code generated by ent, DO NOT EDIT.

package dao

import (
	"aisecurity/ent/dao/admin"
	"aisecurity/ent/dao/eventlevel"
	"aisecurity/ent/dao/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EventLevelQuery is the builder for querying EventLevel entities.
type EventLevelQuery struct {
	config
	ctx         *QueryContext
	order       []eventlevel.OrderOption
	inters      []Interceptor
	predicates  []predicate.EventLevel
	withCreator *AdminQuery
	withUpdater *AdminQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EventLevelQuery builder.
func (elq *EventLevelQuery) Where(ps ...predicate.EventLevel) *EventLevelQuery {
	elq.predicates = append(elq.predicates, ps...)
	return elq
}

// Limit the number of records to be returned by this query.
func (elq *EventLevelQuery) Limit(limit int) *EventLevelQuery {
	elq.ctx.Limit = &limit
	return elq
}

// Offset to start from.
func (elq *EventLevelQuery) Offset(offset int) *EventLevelQuery {
	elq.ctx.Offset = &offset
	return elq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (elq *EventLevelQuery) Unique(unique bool) *EventLevelQuery {
	elq.ctx.Unique = &unique
	return elq
}

// Order specifies how the records should be ordered.
func (elq *EventLevelQuery) Order(o ...eventlevel.OrderOption) *EventLevelQuery {
	elq.order = append(elq.order, o...)
	return elq
}

// QueryCreator chains the current query on the "creator" edge.
func (elq *EventLevelQuery) QueryCreator() *AdminQuery {
	query := (&AdminClient{config: elq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := elq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := elq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(eventlevel.Table, eventlevel.FieldID, selector),
			sqlgraph.To(admin.Table, admin.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, eventlevel.CreatorTable, eventlevel.CreatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(elq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryUpdater chains the current query on the "updater" edge.
func (elq *EventLevelQuery) QueryUpdater() *AdminQuery {
	query := (&AdminClient{config: elq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := elq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := elq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(eventlevel.Table, eventlevel.FieldID, selector),
			sqlgraph.To(admin.Table, admin.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, eventlevel.UpdaterTable, eventlevel.UpdaterColumn),
		)
		fromU = sqlgraph.SetNeighbors(elq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first EventLevel entity from the query.
// Returns a *NotFoundError when no EventLevel was found.
func (elq *EventLevelQuery) First(ctx context.Context) (*EventLevel, error) {
	nodes, err := elq.Limit(1).All(setContextOp(ctx, elq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{eventlevel.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (elq *EventLevelQuery) FirstX(ctx context.Context) *EventLevel {
	node, err := elq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EventLevel ID from the query.
// Returns a *NotFoundError when no EventLevel ID was found.
func (elq *EventLevelQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = elq.Limit(1).IDs(setContextOp(ctx, elq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{eventlevel.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (elq *EventLevelQuery) FirstIDX(ctx context.Context) int {
	id, err := elq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EventLevel entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one EventLevel entity is found.
// Returns a *NotFoundError when no EventLevel entities are found.
func (elq *EventLevelQuery) Only(ctx context.Context) (*EventLevel, error) {
	nodes, err := elq.Limit(2).All(setContextOp(ctx, elq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{eventlevel.Label}
	default:
		return nil, &NotSingularError{eventlevel.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (elq *EventLevelQuery) OnlyX(ctx context.Context) *EventLevel {
	node, err := elq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EventLevel ID in the query.
// Returns a *NotSingularError when more than one EventLevel ID is found.
// Returns a *NotFoundError when no entities are found.
func (elq *EventLevelQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = elq.Limit(2).IDs(setContextOp(ctx, elq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{eventlevel.Label}
	default:
		err = &NotSingularError{eventlevel.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (elq *EventLevelQuery) OnlyIDX(ctx context.Context) int {
	id, err := elq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EventLevels.
func (elq *EventLevelQuery) All(ctx context.Context) ([]*EventLevel, error) {
	ctx = setContextOp(ctx, elq.ctx, "All")
	if err := elq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*EventLevel, *EventLevelQuery]()
	return withInterceptors[[]*EventLevel](ctx, elq, qr, elq.inters)
}

// AllX is like All, but panics if an error occurs.
func (elq *EventLevelQuery) AllX(ctx context.Context) []*EventLevel {
	nodes, err := elq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EventLevel IDs.
func (elq *EventLevelQuery) IDs(ctx context.Context) (ids []int, err error) {
	if elq.ctx.Unique == nil && elq.path != nil {
		elq.Unique(true)
	}
	ctx = setContextOp(ctx, elq.ctx, "IDs")
	if err = elq.Select(eventlevel.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (elq *EventLevelQuery) IDsX(ctx context.Context) []int {
	ids, err := elq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (elq *EventLevelQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, elq.ctx, "Count")
	if err := elq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, elq, querierCount[*EventLevelQuery](), elq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (elq *EventLevelQuery) CountX(ctx context.Context) int {
	count, err := elq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (elq *EventLevelQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, elq.ctx, "Exist")
	switch _, err := elq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("dao: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (elq *EventLevelQuery) ExistX(ctx context.Context) bool {
	exist, err := elq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EventLevelQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (elq *EventLevelQuery) Clone() *EventLevelQuery {
	if elq == nil {
		return nil
	}
	return &EventLevelQuery{
		config:      elq.config,
		ctx:         elq.ctx.Clone(),
		order:       append([]eventlevel.OrderOption{}, elq.order...),
		inters:      append([]Interceptor{}, elq.inters...),
		predicates:  append([]predicate.EventLevel{}, elq.predicates...),
		withCreator: elq.withCreator.Clone(),
		withUpdater: elq.withUpdater.Clone(),
		// clone intermediate query.
		sql:  elq.sql.Clone(),
		path: elq.path,
	}
}

// WithCreator tells the query-builder to eager-load the nodes that are connected to
// the "creator" edge. The optional arguments are used to configure the query builder of the edge.
func (elq *EventLevelQuery) WithCreator(opts ...func(*AdminQuery)) *EventLevelQuery {
	query := (&AdminClient{config: elq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	elq.withCreator = query
	return elq
}

// WithUpdater tells the query-builder to eager-load the nodes that are connected to
// the "updater" edge. The optional arguments are used to configure the query builder of the edge.
func (elq *EventLevelQuery) WithUpdater(opts ...func(*AdminQuery)) *EventLevelQuery {
	query := (&AdminClient{config: elq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	elq.withUpdater = query
	return elq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EventLevel.Query().
//		GroupBy(eventlevel.FieldCreateTime).
//		Aggregate(dao.Count()).
//		Scan(ctx, &v)
func (elq *EventLevelQuery) GroupBy(field string, fields ...string) *EventLevelGroupBy {
	elq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &EventLevelGroupBy{build: elq}
	grbuild.flds = &elq.ctx.Fields
	grbuild.label = eventlevel.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.EventLevel.Query().
//		Select(eventlevel.FieldCreateTime).
//		Scan(ctx, &v)
func (elq *EventLevelQuery) Select(fields ...string) *EventLevelSelect {
	elq.ctx.Fields = append(elq.ctx.Fields, fields...)
	sbuild := &EventLevelSelect{EventLevelQuery: elq}
	sbuild.label = eventlevel.Label
	sbuild.flds, sbuild.scan = &elq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a EventLevelSelect configured with the given aggregations.
func (elq *EventLevelQuery) Aggregate(fns ...AggregateFunc) *EventLevelSelect {
	return elq.Select().Aggregate(fns...)
}

func (elq *EventLevelQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range elq.inters {
		if inter == nil {
			return fmt.Errorf("dao: uninitialized interceptor (forgotten import dao/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, elq); err != nil {
				return err
			}
		}
	}
	for _, f := range elq.ctx.Fields {
		if !eventlevel.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("dao: invalid field %q for query", f)}
		}
	}
	if elq.path != nil {
		prev, err := elq.path(ctx)
		if err != nil {
			return err
		}
		elq.sql = prev
	}
	return nil
}

func (elq *EventLevelQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*EventLevel, error) {
	var (
		nodes       = []*EventLevel{}
		_spec       = elq.querySpec()
		loadedTypes = [2]bool{
			elq.withCreator != nil,
			elq.withUpdater != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*EventLevel).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &EventLevel{config: elq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, elq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := elq.withCreator; query != nil {
		if err := elq.loadCreator(ctx, query, nodes, nil,
			func(n *EventLevel, e *Admin) { n.Edges.Creator = e }); err != nil {
			return nil, err
		}
	}
	if query := elq.withUpdater; query != nil {
		if err := elq.loadUpdater(ctx, query, nodes, nil,
			func(n *EventLevel, e *Admin) { n.Edges.Updater = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (elq *EventLevelQuery) loadCreator(ctx context.Context, query *AdminQuery, nodes []*EventLevel, init func(*EventLevel), assign func(*EventLevel, *Admin)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EventLevel)
	for i := range nodes {
		fk := nodes[i].CreatorID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(admin.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "creator_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (elq *EventLevelQuery) loadUpdater(ctx context.Context, query *AdminQuery, nodes []*EventLevel, init func(*EventLevel), assign func(*EventLevel, *Admin)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*EventLevel)
	for i := range nodes {
		fk := nodes[i].UpdaterID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(admin.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "updater_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (elq *EventLevelQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := elq.querySpec()
	_spec.Node.Columns = elq.ctx.Fields
	if len(elq.ctx.Fields) > 0 {
		_spec.Unique = elq.ctx.Unique != nil && *elq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, elq.driver, _spec)
}

func (elq *EventLevelQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(eventlevel.Table, eventlevel.Columns, sqlgraph.NewFieldSpec(eventlevel.FieldID, field.TypeInt))
	_spec.From = elq.sql
	if unique := elq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if elq.path != nil {
		_spec.Unique = true
	}
	if fields := elq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, eventlevel.FieldID)
		for i := range fields {
			if fields[i] != eventlevel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if elq.withCreator != nil {
			_spec.Node.AddColumnOnce(eventlevel.FieldCreatorID)
		}
		if elq.withUpdater != nil {
			_spec.Node.AddColumnOnce(eventlevel.FieldUpdaterID)
		}
	}
	if ps := elq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := elq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := elq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := elq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (elq *EventLevelQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(elq.driver.Dialect())
	t1 := builder.Table(eventlevel.Table)
	columns := elq.ctx.Fields
	if len(columns) == 0 {
		columns = eventlevel.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if elq.sql != nil {
		selector = elq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if elq.ctx.Unique != nil && *elq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range elq.predicates {
		p(selector)
	}
	for _, p := range elq.order {
		p(selector)
	}
	if offset := elq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := elq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EventLevelGroupBy is the group-by builder for EventLevel entities.
type EventLevelGroupBy struct {
	selector
	build *EventLevelQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (elgb *EventLevelGroupBy) Aggregate(fns ...AggregateFunc) *EventLevelGroupBy {
	elgb.fns = append(elgb.fns, fns...)
	return elgb
}

// Scan applies the selector query and scans the result into the given value.
func (elgb *EventLevelGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, elgb.build.ctx, "GroupBy")
	if err := elgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EventLevelQuery, *EventLevelGroupBy](ctx, elgb.build, elgb, elgb.build.inters, v)
}

func (elgb *EventLevelGroupBy) sqlScan(ctx context.Context, root *EventLevelQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(elgb.fns))
	for _, fn := range elgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*elgb.flds)+len(elgb.fns))
		for _, f := range *elgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*elgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := elgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// EventLevelSelect is the builder for selecting fields of EventLevel entities.
type EventLevelSelect struct {
	*EventLevelQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (els *EventLevelSelect) Aggregate(fns ...AggregateFunc) *EventLevelSelect {
	els.fns = append(els.fns, fns...)
	return els
}

// Scan applies the selector query and scans the result into the given value.
func (els *EventLevelSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, els.ctx, "Select")
	if err := els.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*EventLevelQuery, *EventLevelSelect](ctx, els.EventLevelQuery, els, els.inters, v)
}

func (els *EventLevelSelect) sqlScan(ctx context.Context, root *EventLevelQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(els.fns))
	for _, fn := range els.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*els.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := els.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
