// Code generated by ent, DO NOT EDIT.

package dao

import (
	"aisecurity/ent/dao/admin"
	"aisecurity/ent/dao/sweep"
	"aisecurity/ent/dao/sweepresult"
	"aisecurity/ent/dao/sweepschedule"
	"aisecurity/structs/types"
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// SweepResult is the model entity for the SweepResult schema.
type SweepResult struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 创建时间
	CreateTime time.Time `json:"create_time"`
	// 创建者
	CreatorID int `json:"creator_id"`
	// 删除时间
	DeleteTime *time.Time `json:"delete_time"`
	// 最后更新者
	UpdaterID int `json:"updater_id"`
	// 最后更新时间
	UpdateTime time.Time `json:"update_time"`
	// 排查模板ID
	SweepID int `json:"sweep_id"`
	// 排查任务ID
	SweepScheduleID int `json:"sweep_schedule_id"`
	// 签到时间
	CheckInTime time.Time `json:"check_in_time"`
	// 签到照片
	CheckInImage types.UploadedImage `json:"check_in_image"`
	// 排查内容
	SweepJobs []*types.SweepJob `json:"sweep_jobs"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SweepResultQuery when eager-loading is set.
	Edges        SweepResultEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SweepResultEdges holds the relations/edges for other nodes in the graph.
type SweepResultEdges struct {
	// Creator holds the value of the creator edge.
	Creator *Admin `json:"creator,omitempty"`
	// Updater holds the value of the updater edge.
	Updater *Admin `json:"updater,omitempty"`
	// Sweep holds the value of the sweep edge.
	Sweep *Sweep `json:"sweep,omitempty"`
	// SweepSchedule holds the value of the sweep_schedule edge.
	SweepSchedule *SweepSchedule `json:"sweep_schedule,omitempty"`
	// SweepResultDetails holds the value of the sweep_result_details edge.
	SweepResultDetails []*SweepResultDetails `json:"sweep_result_details,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// CreatorOrErr returns the Creator value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SweepResultEdges) CreatorOrErr() (*Admin, error) {
	if e.loadedTypes[0] {
		if e.Creator == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: admin.Label}
		}
		return e.Creator, nil
	}
	return nil, &NotLoadedError{edge: "creator"}
}

// UpdaterOrErr returns the Updater value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SweepResultEdges) UpdaterOrErr() (*Admin, error) {
	if e.loadedTypes[1] {
		if e.Updater == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: admin.Label}
		}
		return e.Updater, nil
	}
	return nil, &NotLoadedError{edge: "updater"}
}

// SweepOrErr returns the Sweep value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SweepResultEdges) SweepOrErr() (*Sweep, error) {
	if e.loadedTypes[2] {
		if e.Sweep == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: sweep.Label}
		}
		return e.Sweep, nil
	}
	return nil, &NotLoadedError{edge: "sweep"}
}

// SweepScheduleOrErr returns the SweepSchedule value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SweepResultEdges) SweepScheduleOrErr() (*SweepSchedule, error) {
	if e.loadedTypes[3] {
		if e.SweepSchedule == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: sweepschedule.Label}
		}
		return e.SweepSchedule, nil
	}
	return nil, &NotLoadedError{edge: "sweep_schedule"}
}

// SweepResultDetailsOrErr returns the SweepResultDetails value or an error if the edge
// was not loaded in eager-loading.
func (e SweepResultEdges) SweepResultDetailsOrErr() ([]*SweepResultDetails, error) {
	if e.loadedTypes[4] {
		return e.SweepResultDetails, nil
	}
	return nil, &NotLoadedError{edge: "sweep_result_details"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SweepResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sweepresult.FieldCheckInImage, sweepresult.FieldSweepJobs:
			values[i] = new([]byte)
		case sweepresult.FieldID, sweepresult.FieldCreatorID, sweepresult.FieldUpdaterID, sweepresult.FieldSweepID, sweepresult.FieldSweepScheduleID:
			values[i] = new(sql.NullInt64)
		case sweepresult.FieldCreateTime, sweepresult.FieldDeleteTime, sweepresult.FieldUpdateTime, sweepresult.FieldCheckInTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SweepResult fields.
func (sr *SweepResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sweepresult.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			sr.ID = int(value.Int64)
		case sweepresult.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field create_time", values[i])
			} else if value.Valid {
				sr.CreateTime = value.Time
			}
		case sweepresult.FieldCreatorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creator_id", values[i])
			} else if value.Valid {
				sr.CreatorID = int(value.Int64)
			}
		case sweepresult.FieldDeleteTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field delete_time", values[i])
			} else if value.Valid {
				sr.DeleteTime = new(time.Time)
				*sr.DeleteTime = value.Time
			}
		case sweepresult.FieldUpdaterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updater_id", values[i])
			} else if value.Valid {
				sr.UpdaterID = int(value.Int64)
			}
		case sweepresult.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field update_time", values[i])
			} else if value.Valid {
				sr.UpdateTime = value.Time
			}
		case sweepresult.FieldSweepID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sweep_id", values[i])
			} else if value.Valid {
				sr.SweepID = int(value.Int64)
			}
		case sweepresult.FieldSweepScheduleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sweep_schedule_id", values[i])
			} else if value.Valid {
				sr.SweepScheduleID = int(value.Int64)
			}
		case sweepresult.FieldCheckInTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field check_in_time", values[i])
			} else if value.Valid {
				sr.CheckInTime = value.Time
			}
		case sweepresult.FieldCheckInImage:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field check_in_image", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &sr.CheckInImage); err != nil {
					return fmt.Errorf("unmarshal field check_in_image: %w", err)
				}
			}
		case sweepresult.FieldSweepJobs:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field sweep_jobs", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &sr.SweepJobs); err != nil {
					return fmt.Errorf("unmarshal field sweep_jobs: %w", err)
				}
			}
		default:
			sr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SweepResult.
// This includes values selected through modifiers, order, etc.
func (sr *SweepResult) Value(name string) (ent.Value, error) {
	return sr.selectValues.Get(name)
}

// QueryCreator queries the "creator" edge of the SweepResult entity.
func (sr *SweepResult) QueryCreator() *AdminQuery {
	return NewSweepResultClient(sr.config).QueryCreator(sr)
}

// QueryUpdater queries the "updater" edge of the SweepResult entity.
func (sr *SweepResult) QueryUpdater() *AdminQuery {
	return NewSweepResultClient(sr.config).QueryUpdater(sr)
}

// QuerySweep queries the "sweep" edge of the SweepResult entity.
func (sr *SweepResult) QuerySweep() *SweepQuery {
	return NewSweepResultClient(sr.config).QuerySweep(sr)
}

// QuerySweepSchedule queries the "sweep_schedule" edge of the SweepResult entity.
func (sr *SweepResult) QuerySweepSchedule() *SweepScheduleQuery {
	return NewSweepResultClient(sr.config).QuerySweepSchedule(sr)
}

// QuerySweepResultDetails queries the "sweep_result_details" edge of the SweepResult entity.
func (sr *SweepResult) QuerySweepResultDetails() *SweepResultDetailsQuery {
	return NewSweepResultClient(sr.config).QuerySweepResultDetails(sr)
}

// Update returns a builder for updating this SweepResult.
// Note that you need to call SweepResult.Unwrap() before calling this method if this SweepResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (sr *SweepResult) Update() *SweepResultUpdateOne {
	return NewSweepResultClient(sr.config).UpdateOne(sr)
}

// Unwrap unwraps the SweepResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (sr *SweepResult) Unwrap() *SweepResult {
	_tx, ok := sr.config.driver.(*txDriver)
	if !ok {
		panic("dao: SweepResult is not a transactional entity")
	}
	sr.config.driver = _tx.drv
	return sr
}

// String implements the fmt.Stringer.
func (sr *SweepResult) String() string {
	var builder strings.Builder
	builder.WriteString("SweepResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", sr.ID))
	builder.WriteString("create_time=")
	builder.WriteString(sr.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("creator_id=")
	builder.WriteString(fmt.Sprintf("%v", sr.CreatorID))
	builder.WriteString(", ")
	if v := sr.DeleteTime; v != nil {
		builder.WriteString("delete_time=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("updater_id=")
	builder.WriteString(fmt.Sprintf("%v", sr.UpdaterID))
	builder.WriteString(", ")
	builder.WriteString("update_time=")
	builder.WriteString(sr.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("sweep_id=")
	builder.WriteString(fmt.Sprintf("%v", sr.SweepID))
	builder.WriteString(", ")
	builder.WriteString("sweep_schedule_id=")
	builder.WriteString(fmt.Sprintf("%v", sr.SweepScheduleID))
	builder.WriteString(", ")
	builder.WriteString("check_in_time=")
	builder.WriteString(sr.CheckInTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("check_in_image=")
	builder.WriteString(fmt.Sprintf("%v", sr.CheckInImage))
	builder.WriteString(", ")
	builder.WriteString("sweep_jobs=")
	builder.WriteString(fmt.Sprintf("%v", sr.SweepJobs))
	builder.WriteByte(')')
	return builder.String()
}

// SweepResults is a parsable slice of SweepResult.
type SweepResults []*SweepResult
