// Code generated by ent, DO NOT EDIT.

package risk

import (
	"aisecurity/properties/maintain_status"
	"aisecurity/structs/types"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the risk type in the database.
	Label = "risk"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldCreatorID holds the string denoting the creator_id field in the database.
	FieldCreatorID = "creator_id"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldUpdaterID holds the string denoting the updater_id field in the database.
	FieldUpdaterID = "updater_id"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldImages holds the string denoting the images field in the database.
	FieldImages = "images"
	// FieldRiskCategoryID holds the string denoting the risk_category_id field in the database.
	FieldRiskCategoryID = "risk_category_id"
	// FieldRiskLocationID holds the string denoting the risk_location_id field in the database.
	FieldRiskLocationID = "risk_location_id"
	// FieldMaintainerID holds the string denoting the maintainer_id field in the database.
	FieldMaintainerID = "maintainer_id"
	// FieldMeasures holds the string denoting the measures field in the database.
	FieldMeasures = "measures"
	// FieldMaintainStatus holds the string denoting the maintain_status field in the database.
	FieldMaintainStatus = "maintain_status"
	// FieldDueTime holds the string denoting the due_time field in the database.
	FieldDueTime = "due_time"
	// EdgeCreator holds the string denoting the creator edge name in mutations.
	EdgeCreator = "creator"
	// EdgeUpdater holds the string denoting the updater edge name in mutations.
	EdgeUpdater = "updater"
	// EdgeRiskCategory holds the string denoting the risk_category edge name in mutations.
	EdgeRiskCategory = "risk_category"
	// EdgeRiskLocation holds the string denoting the risk_location edge name in mutations.
	EdgeRiskLocation = "risk_location"
	// EdgeMaintainer holds the string denoting the maintainer edge name in mutations.
	EdgeMaintainer = "maintainer"
	// Table holds the table name of the risk in the database.
	Table = "risks"
	// CreatorTable is the table that holds the creator relation/edge.
	CreatorTable = "risks"
	// CreatorInverseTable is the table name for the Admin entity.
	// It exists in this package in order to avoid circular dependency with the "admin" package.
	CreatorInverseTable = "admins"
	// CreatorColumn is the table column denoting the creator relation/edge.
	CreatorColumn = "creator_id"
	// UpdaterTable is the table that holds the updater relation/edge.
	UpdaterTable = "risks"
	// UpdaterInverseTable is the table name for the Admin entity.
	// It exists in this package in order to avoid circular dependency with the "admin" package.
	UpdaterInverseTable = "admins"
	// UpdaterColumn is the table column denoting the updater relation/edge.
	UpdaterColumn = "updater_id"
	// RiskCategoryTable is the table that holds the risk_category relation/edge.
	RiskCategoryTable = "risks"
	// RiskCategoryInverseTable is the table name for the RiskCategory entity.
	// It exists in this package in order to avoid circular dependency with the "riskcategory" package.
	RiskCategoryInverseTable = "risk_categories"
	// RiskCategoryColumn is the table column denoting the risk_category relation/edge.
	RiskCategoryColumn = "risk_category_id"
	// RiskLocationTable is the table that holds the risk_location relation/edge.
	RiskLocationTable = "risks"
	// RiskLocationInverseTable is the table name for the RiskLocation entity.
	// It exists in this package in order to avoid circular dependency with the "risklocation" package.
	RiskLocationInverseTable = "risk_locations"
	// RiskLocationColumn is the table column denoting the risk_location relation/edge.
	RiskLocationColumn = "risk_location_id"
	// MaintainerTable is the table that holds the maintainer relation/edge.
	MaintainerTable = "risks"
	// MaintainerInverseTable is the table name for the Admin entity.
	// It exists in this package in order to avoid circular dependency with the "admin" package.
	MaintainerInverseTable = "admins"
	// MaintainerColumn is the table column denoting the maintainer relation/edge.
	MaintainerColumn = "maintainer_id"
)

// Columns holds all SQL columns for risk fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldCreatorID,
	FieldDeleteTime,
	FieldUpdaterID,
	FieldUpdateTime,
	FieldTitle,
	FieldContent,
	FieldImages,
	FieldRiskCategoryID,
	FieldRiskLocationID,
	FieldMaintainerID,
	FieldMeasures,
	FieldMaintainStatus,
	FieldDueTime,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "aisecurity/ent/dao/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// CreatorIDValidator is a validator for the "creator_id" field. It is called by the builders before save.
	CreatorIDValidator func(int) error
	// UpdaterIDValidator is a validator for the "updater_id" field. It is called by the builders before save.
	UpdaterIDValidator func(int) error
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultImages holds the default value on creation for the "images" field.
	DefaultImages []types.UploadedImage
	// RiskCategoryIDValidator is a validator for the "risk_category_id" field. It is called by the builders before save.
	RiskCategoryIDValidator func(int) error
	// RiskLocationIDValidator is a validator for the "risk_location_id" field. It is called by the builders before save.
	RiskLocationIDValidator func(int) error
	// MaintainerIDValidator is a validator for the "maintainer_id" field. It is called by the builders before save.
	MaintainerIDValidator func(int) error
	// DefaultMaintainStatus holds the default value on creation for the "maintain_status" field.
	DefaultMaintainStatus maintain_status.MaintainStatus
	// MaintainStatusValidator is a validator for the "maintain_status" field. It is called by the builders before save.
	MaintainStatusValidator func(int) error
)

// OrderOption defines the ordering options for the Risk queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByCreatorID orders the results by the creator_id field.
func ByCreatorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatorID, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByUpdaterID orders the results by the updater_id field.
func ByUpdaterID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdaterID, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByRiskCategoryID orders the results by the risk_category_id field.
func ByRiskCategoryID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRiskCategoryID, opts...).ToFunc()
}

// ByRiskLocationID orders the results by the risk_location_id field.
func ByRiskLocationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRiskLocationID, opts...).ToFunc()
}

// ByMaintainerID orders the results by the maintainer_id field.
func ByMaintainerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaintainerID, opts...).ToFunc()
}

// ByMeasures orders the results by the measures field.
func ByMeasures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeasures, opts...).ToFunc()
}

// ByMaintainStatus orders the results by the maintain_status field.
func ByMaintainStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaintainStatus, opts...).ToFunc()
}

// ByDueTime orders the results by the due_time field.
func ByDueTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDueTime, opts...).ToFunc()
}

// ByCreatorField orders the results by creator field.
func ByCreatorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCreatorStep(), sql.OrderByField(field, opts...))
	}
}

// ByUpdaterField orders the results by updater field.
func ByUpdaterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUpdaterStep(), sql.OrderByField(field, opts...))
	}
}

// ByRiskCategoryField orders the results by risk_category field.
func ByRiskCategoryField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRiskCategoryStep(), sql.OrderByField(field, opts...))
	}
}

// ByRiskLocationField orders the results by risk_location field.
func ByRiskLocationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRiskLocationStep(), sql.OrderByField(field, opts...))
	}
}

// ByMaintainerField orders the results by maintainer field.
func ByMaintainerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMaintainerStep(), sql.OrderByField(field, opts...))
	}
}
func newCreatorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CreatorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, CreatorTable, CreatorColumn),
	)
}
func newUpdaterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UpdaterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UpdaterTable, UpdaterColumn),
	)
}
func newRiskCategoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RiskCategoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RiskCategoryTable, RiskCategoryColumn),
	)
}
func newRiskLocationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RiskLocationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, RiskLocationTable, RiskLocationColumn),
	)
}
func newMaintainerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MaintainerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MaintainerTable, MaintainerColumn),
	)
}
