// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Admin is the predicate function for admin builders.
type Admin func(*sql.Selector)

// Area is the predicate function for area builders.
type Area func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Device is the predicate function for device builders.
type Device func(*sql.Selector)

// DeviceInstallation is the predicate function for deviceinstallation builders.
type DeviceInstallation func(*sql.Selector)

// Employee is the predicate function for employee builders.
type Employee func(*sql.Selector)

// Event is the predicate function for event builders.
type Event func(*sql.Selector)

// EventLevel is the predicate function for eventlevel builders.
type EventLevel func(*sql.Selector)

// EventLog is the predicate function for eventlog builders.
type EventLog func(*sql.Selector)

// Fixing is the predicate function for fixing builders.
type Fixing func(*sql.Selector)

// Occupation is the predicate function for occupation builders.
type Occupation func(*sql.Selector)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Risk is the predicate function for risk builders.
type Risk func(*sql.Selector)

// RiskCategory is the predicate function for riskcategory builders.
type RiskCategory func(*sql.Selector)

// RiskLocation is the predicate function for risklocation builders.
type RiskLocation func(*sql.Selector)

// Sweep is the predicate function for sweep builders.
type Sweep func(*sql.Selector)

// SweepResult is the predicate function for sweepresult builders.
type SweepResult func(*sql.Selector)

// SweepResultDetails is the predicate function for sweepresultdetails builders.
type SweepResultDetails func(*sql.Selector)

// SweepSchedule is the predicate function for sweepschedule builders.
type SweepSchedule func(*sql.Selector)

// Video is the predicate function for video builders.
type Video func(*sql.Selector)
